version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/timezone.cnf:/etc/mysql/conf.d/timezone.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: influx
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:1.17
    ports:
      - "8000:80"
    volumes:
      - ".:/app"
      - "./docker/nginx/nginx-config:/etc/nginx/conf.d/default.conf"

  php:
    build: ./docker/php
    user: "1000"
    ports:
      - "9000:9000"
    volumes:
      - ".:/app"
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    working_dir: /app

  node:
    image: "node:11.10"
    user: "1000"
    ports:
      - "8081:8081"
    volumes:
      - ".:/app"
    working_dir: /app
    command: npm run dev-server
